# Generated by Django 4.2.28 on 2026-03-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(default='', max_length=300),
        ),
    ]
