# Generated by Django 4.2.28 on 2026-03-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_add_subject_to_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ended_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
